#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Ch000Out

#include "Basic.hpp"

#include "ABP_Ch000Out_classes.hpp"
#include "ABP_Ch000Out_parameters.hpp"


namespace SDK
{

// Function ABP_Ch000Out.ABP_Ch000Out_C.ExecuteUbergraph_ABP_Ch000Out
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_Ch000Out_C::ExecuteUbergraph_ABP_Ch000Out(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Ch000Out_C", "ExecuteUbergraph_ABP_Ch000Out");

	Params::ABP_Ch000Out_C_ExecuteUbergraph_ABP_Ch000Out Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_Ch000Out.ABP_Ch000Out_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_Ch000Out_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Ch000Out_C", "AnimGraph");

	Params::ABP_Ch000Out_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

