#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Ch000_LayerInterface

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_Ch000_LayerInterface.ABP_Ch000_LayerInterface_C
// 0x0000 (0x0028 - 0x0028)
class IABP_Ch000_LayerInterface_C final : public IAnimLayerInterface
{
public:
	void ActionCustom(const struct FPoseLink& InPose, struct FPoseLink* ActionCustom_0);
	void NagaraBlend(const struct FPoseLink& LowerBody, const struct FPoseLink& UpperBody, float UpperWeights, struct FPoseLink* NagaraBlend_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_Ch000_LayerInterface_C">();
	}
	static class IABP_Ch000_LayerInterface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IABP_Ch000_LayerInterface_C>();
	}
};
static_assert(alignof(IABP_Ch000_LayerInterface_C) == 0x000008, "Wrong alignment on IABP_Ch000_LayerInterface_C");
static_assert(sizeof(IABP_Ch000_LayerInterface_C) == 0x000028, "Wrong size on IABP_Ch000_LayerInterface_C");

}

