#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Ch000_LayerInterface

#include "Basic.hpp"

#include "ABP_Ch000_LayerInterface_classes.hpp"
#include "ABP_Ch000_LayerInterface_parameters.hpp"


namespace SDK
{

// Function ABP_Ch000_LayerInterface.ABP_Ch000_LayerInterface_C.ActionCustom
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        ActionCustom_0                                         (Parm, OutParm, NoDestructor)

void IABP_Ch000_LayerInterface_C::ActionCustom(const struct FPoseLink& InPose, struct FPoseLink* ActionCustom_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Ch000_LayerInterface_C", "ActionCustom");

	Params::ABP_Ch000_LayerInterface_C_ActionCustom Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (ActionCustom_0 != nullptr)
		*ActionCustom_0 = std::move(Parms.ActionCustom_0);
}


// Function ABP_Ch000_LayerInterface.ABP_Ch000_LayerInterface_C.NagaraBlend
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        LowerBody                                              (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        UpperBody                                              (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   UpperWeights                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FPoseLink                        NagaraBlend_0                                          (Parm, OutParm, NoDestructor)

void IABP_Ch000_LayerInterface_C::NagaraBlend(const struct FPoseLink& LowerBody, const struct FPoseLink& UpperBody, float UpperWeights, struct FPoseLink* NagaraBlend_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Ch000_LayerInterface_C", "NagaraBlend");

	Params::ABP_Ch000_LayerInterface_C_NagaraBlend Parms{};

	Parms.LowerBody = std::move(LowerBody);
	Parms.UpperBody = std::move(UpperBody);
	Parms.UpperWeights = UpperWeights;

	UObject::ProcessEvent(Func, &Parms);

	if (NagaraBlend_0 != nullptr)
		*NagaraBlend_0 = std::move(Parms.NagaraBlend_0);
}

}

