#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionSuperJumpFall

#include "Basic.hpp"

#include "BP_ActionSuperJumpFall_classes.hpp"
#include "BP_ActionSuperJumpFall_parameters.hpp"


namespace SDK
{

// Function BP_ActionSuperJumpFall.BP_ActionSuperJumpFall_C.ExecuteUbergraph_BP_ActionSuperJumpFall
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionSuperJumpFall_C::ExecuteUbergraph_BP_ActionSuperJumpFall(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionSuperJumpFall_C", "ExecuteUbergraph_BP_ActionSuperJumpFall");

	Params::BP_ActionSuperJumpFall_C_ExecuteUbergraph_BP_ActionSuperJumpFall Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionSuperJumpFall.BP_ActionSuperJumpFall_C.BP_OnLandingEvent
// (Event, Protected, BlueprintEvent)

void UBP_ActionSuperJumpFall_C::BP_OnLandingEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionSuperJumpFall_C", "BP_OnLandingEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionSuperJumpFall.BP_ActionSuperJumpFall_C.BP_ActionMain
// (Event, Protected, BlueprintEvent)

void UBP_ActionSuperJumpFall_C::BP_ActionMain()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionSuperJumpFall_C", "BP_ActionMain");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionSuperJumpFall.BP_ActionSuperJumpFall_C.BP_OnBeginAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class FName                             PrevAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionSuperJumpFall_C::BP_OnBeginAction(const class FName& PrevAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionSuperJumpFall_C", "BP_OnBeginAction");

	Params::BP_ActionSuperJumpFall_C_BP_OnBeginAction Parms{};

	Parms.PrevAction = PrevAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionSuperJumpFall.BP_ActionSuperJumpFall_C.UpdateCo-Routine
// (BlueprintCallable, BlueprintEvent)

void UBP_ActionSuperJumpFall_C::UpdateCoMinusRoutine()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionSuperJumpFall_C", "UpdateCo-Routine");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionSuperJumpFall.BP_ActionSuperJumpFall_C.BP_OnEndAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class FName                             NextAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionSuperJumpFall_C::BP_OnEndAction(const class FName& NextAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionSuperJumpFall_C", "BP_OnEndAction");

	Params::BP_ActionSuperJumpFall_C_BP_OnEndAction Parms{};

	Parms.NextAction = NextAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionSuperJumpFall.BP_ActionSuperJumpFall_C.BP_IsEnableShiftAction
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FName                             NextAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UBP_ActionSuperJumpFall_C::BP_IsEnableShiftAction(const class FName& NextAction) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionSuperJumpFall_C", "BP_IsEnableShiftAction");

	Params::BP_ActionSuperJumpFall_C_BP_IsEnableShiftAction Parms{};

	Parms.NextAction = NextAction;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

