#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionGuard

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "InGameModule_classes.hpp"
#include "CommonModule_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ActionGuard.BP_ActionGuard_C
// 0x0008 (0x0358 - 0x0350)
class UBP_ActionGuard_C final : public UActionAttackBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0350(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_ActionGuard(int32 EntryPoint);
	void BP_OnEndAction(const class FName& NextAction);
	void BP_OnBeginAction(const class FName& PrevAction);
	void BP_ActionMain();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ActionGuard_C">();
	}
	static class UBP_ActionGuard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActionGuard_C>();
	}
};
static_assert(alignof(UBP_ActionGuard_C) == 0x000008, "Wrong alignment on UBP_ActionGuard_C");
static_assert(sizeof(UBP_ActionGuard_C) == 0x000358, "Wrong size on UBP_ActionGuard_C");
static_assert(offsetof(UBP_ActionGuard_C, UberGraphFrame) == 0x000350, "Member 'UBP_ActionGuard_C::UberGraphFrame' has a wrong offset!");

}

