#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionFailedWallThrough

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "InGameModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ActionFailedWallThrough.BP_ActionFailedWallThrough_C
// 0x0008 (0x01B8 - 0x01B0)
class UBP_ActionFailedWallThrough_C final : public UActionFailedWallThrough
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x01B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_ActionFailedWallThrough(int32 EntryPoint);
	void BP_OnEndAction(const class FName& NextAction);
	void BP_ActionMain();
	void BP_OnBeginAction(const class FName& PrevAction);

	bool BP_IsEnableShiftAction(const class FName& NextAction) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ActionFailedWallThrough_C">();
	}
	static class UBP_ActionFailedWallThrough_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActionFailedWallThrough_C>();
	}
};
static_assert(alignof(UBP_ActionFailedWallThrough_C) == 0x000008, "Wrong alignment on UBP_ActionFailedWallThrough_C");
static_assert(sizeof(UBP_ActionFailedWallThrough_C) == 0x0001B8, "Wrong size on UBP_ActionFailedWallThrough_C");
static_assert(offsetof(UBP_ActionFailedWallThrough_C, UberGraphFrame) == 0x0001B0, "Member 'UBP_ActionFailedWallThrough_C::UberGraphFrame' has a wrong offset!");

}

