#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionAttack_Finisher

#include "Basic.hpp"

#include "BP_ActionAttack_Finisher_classes.hpp"
#include "BP_ActionAttack_Finisher_parameters.hpp"


namespace SDK
{

// Function BP_ActionAttack_Finisher.BP_ActionAttack_Finisher_C.ExecuteUbergraph_BP_ActionAttack_Finisher
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionAttack_Finisher_C::ExecuteUbergraph_BP_ActionAttack_Finisher(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionAttack_Finisher_C", "ExecuteUbergraph_BP_ActionAttack_Finisher");

	Params::BP_ActionAttack_Finisher_C_ExecuteUbergraph_BP_ActionAttack_Finisher Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionAttack_Finisher.BP_ActionAttack_Finisher_C.BP_OnBootDamage
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bSuperArmor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bZeroDamage                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_ActionAttack_Finisher_C::BP_OnBootDamage(bool bSuperArmor, bool bZeroDamage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionAttack_Finisher_C", "BP_OnBootDamage");

	Params::BP_ActionAttack_Finisher_C_BP_OnBootDamage Parms{};

	Parms.bSuperArmor = bSuperArmor;
	Parms.bZeroDamage = bZeroDamage;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionAttack_Finisher.BP_ActionAttack_Finisher_C.BP_OnHitAttackEvent
// (Event, Protected, BlueprintEvent)
// Parameters:
// struct FVector                          HitLocation                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             ProjectileName                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ACharacterBattle*                 HitCharacter                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionAttack_Finisher_C::BP_OnHitAttackEvent(const struct FVector& HitLocation, class FName ProjectileName, class ACharacterBattle* HitCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionAttack_Finisher_C", "BP_OnHitAttackEvent");

	Params::BP_ActionAttack_Finisher_C_BP_OnHitAttackEvent Parms{};

	Parms.HitLocation = std::move(HitLocation);
	Parms.ProjectileName = ProjectileName;
	Parms.HitCharacter = HitCharacter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionAttack_Finisher.BP_ActionAttack_Finisher_C.BP_OnEndAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class FName                             NextAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionAttack_Finisher_C::BP_OnEndAction(const class FName& NextAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionAttack_Finisher_C", "BP_OnEndAction");

	Params::BP_ActionAttack_Finisher_C_BP_OnEndAction Parms{};

	Parms.NextAction = NextAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionAttack_Finisher.BP_ActionAttack_Finisher_C.BP_OnNotificationAttackDedicatedEvent
// (Event, Protected, BlueprintEvent)
// Parameters:
// EAttackDedicatedEventId                 ID                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionAttack_Finisher_C::BP_OnNotificationAttackDedicatedEvent(EAttackDedicatedEventId ID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionAttack_Finisher_C", "BP_OnNotificationAttackDedicatedEvent");

	Params::BP_ActionAttack_Finisher_C_BP_OnNotificationAttackDedicatedEvent Parms{};

	Parms.ID = ID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionAttack_Finisher.BP_ActionAttack_Finisher_C.RecoverGuardPointEvent_Remote
// (BlueprintCallable, BlueprintEvent)

void UBP_ActionAttack_Finisher_C::RecoverGuardPointEvent_Remote()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionAttack_Finisher_C", "RecoverGuardPointEvent_Remote");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionAttack_Finisher.BP_ActionAttack_Finisher_C.TickWaitFinishEvent
// (BlueprintCallable, BlueprintEvent)

void UBP_ActionAttack_Finisher_C::TickWaitFinishEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionAttack_Finisher_C", "TickWaitFinishEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionAttack_Finisher.BP_ActionAttack_Finisher_C.BP_OnChangeAttackPhase
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   NextPhase                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionAttack_Finisher_C::BP_OnChangeAttackPhase(int32 NextPhase)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionAttack_Finisher_C", "BP_OnChangeAttackPhase");

	Params::BP_ActionAttack_Finisher_C_BP_OnChangeAttackPhase Parms{};

	Parms.NextPhase = NextPhase;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionAttack_Finisher.BP_ActionAttack_Finisher_C.BP_OnChangeAttackPhaseForRemote
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   NextPhase                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionAttack_Finisher_C::BP_OnChangeAttackPhaseForRemote(int32 NextPhase)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionAttack_Finisher_C", "BP_OnChangeAttackPhaseForRemote");

	Params::BP_ActionAttack_Finisher_C_BP_OnChangeAttackPhaseForRemote Parms{};

	Parms.NextPhase = NextPhase;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionAttack_Finisher.BP_ActionAttack_Finisher_C.BP_OnBeginAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class FName                             PrevAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionAttack_Finisher_C::BP_OnBeginAction(const class FName& PrevAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionAttack_Finisher_C", "BP_OnBeginAction");

	Params::BP_ActionAttack_Finisher_C_BP_OnBeginAction Parms{};

	Parms.PrevAction = PrevAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionAttack_Finisher.BP_ActionAttack_Finisher_C.BP_ActionMain
// (Event, Protected, BlueprintEvent)

void UBP_ActionAttack_Finisher_C::BP_ActionMain()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionAttack_Finisher_C", "BP_ActionMain");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionAttack_Finisher.BP_ActionAttack_Finisher_C.SetInteractedTarget
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bInteract                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_ActionAttack_Finisher_C::SetInteractedTarget(bool bInteract)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionAttack_Finisher_C", "SetInteractedTarget");

	Params::BP_ActionAttack_Finisher_C_SetInteractedTarget Parms{};

	Parms.bInteract = bInteract;

	UObject::ProcessEvent(Func, &Parms);
}

}

