#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CC_Rule_Respawned

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameModule_structs.hpp"
#include "InGameModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CC_Rule_Respawned.BP_CC_Rule_Respawned_C
// 0x0028 (0x0128 - 0x0100)
class UBP_CC_Rule_Respawned_C final : public UCharacterConditionBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0100(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FTransitionMaterialScalarParamArgment  Argment;                                           // 0x0108(0x0020)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NoDestructor)

public:
	void ExecuteUbergraph_BP_CC_Rule_Respawned(int32 EntryPoint);
	void BP_OnEndCondition();
	void BP_OnBeginCondition();
	void BP_OnUpdateIntervalValue(float Value);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CC_Rule_Respawned_C">();
	}
	static class UBP_CC_Rule_Respawned_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CC_Rule_Respawned_C>();
	}
};
static_assert(alignof(UBP_CC_Rule_Respawned_C) == 0x000008, "Wrong alignment on UBP_CC_Rule_Respawned_C");
static_assert(sizeof(UBP_CC_Rule_Respawned_C) == 0x000128, "Wrong size on UBP_CC_Rule_Respawned_C");
static_assert(offsetof(UBP_CC_Rule_Respawned_C, UberGraphFrame) == 0x000100, "Member 'UBP_CC_Rule_Respawned_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_CC_Rule_Respawned_C, Argment) == 0x000108, "Member 'UBP_CC_Rule_Respawned_C::Argment' has a wrong offset!");

}

