#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CC_PoizonMist

#include "Basic.hpp"

#include "BP_CC_PoizonMist_classes.hpp"
#include "BP_CC_PoizonMist_parameters.hpp"


namespace SDK
{

// Function BP_CC_PoizonMist.BP_CC_PoizonMist_C.ExecuteUbergraph_BP_CC_PoizonMist
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_CC_PoizonMist_C::ExecuteUbergraph_BP_CC_PoizonMist(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CC_PoizonMist_C", "ExecuteUbergraph_BP_CC_PoizonMist");

	Params::BP_CC_PoizonMist_C_ExecuteUbergraph_BP_CC_PoizonMist Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CC_PoizonMist.BP_CC_PoizonMist_C.BP_OnUpdateIntervalValue
// (Event, Protected, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_CC_PoizonMist_C::BP_OnUpdateIntervalValue(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CC_PoizonMist_C", "BP_OnUpdateIntervalValue");

	Params::BP_CC_PoizonMist_C_BP_OnUpdateIntervalValue Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}

}

