#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GUIFunction

#include "Basic.hpp"

#include "BP_GUIFunction_classes.hpp"
#include "BP_GUIFunction_parameters.hpp"


namespace SDK
{

// Function BP_GUIFunction.BP_GUIFunction_C.OpenLevel
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TSoftObjectPtr<class UWorld>            Level                                                  (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ULevelStreaming*                  LevelInstance                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_GUIFunction_C::OpenLevel(TSoftObjectPtr<class UWorld> Level, class UObject* __WorldContext, class ULevelStreaming** LevelInstance)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BP_GUIFunction_C", "OpenLevel");

	Params::BP_GUIFunction_C_OpenLevel Parms{};

	Parms.Level = Level;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (LevelInstance != nullptr)
		*LevelInstance = Parms.LevelInstance;
}


// Function BP_GUIFunction.BP_GUIFunction_C.CloseLevel
// (Static, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             LevelName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_GUIFunction_C::CloseLevel(class FName LevelName, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BP_GUIFunction_C", "CloseLevel");

	Params::BP_GUIFunction_C_CloseLevel Parms{};

	Parms.LevelName = LevelName;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function BP_GUIFunction.BP_GUIFunction_C.GetLevelName
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TSoftObjectPtr<class UWorld>            Level                                                  (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             LevelName                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_GUIFunction_C::GetLevelName(TSoftObjectPtr<class UWorld> Level, class UObject* __WorldContext, class FName* LevelName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BP_GUIFunction_C", "GetLevelName");

	Params::BP_GUIFunction_C_GetLevelName Parms{};

	Parms.Level = Level;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (LevelName != nullptr)
		*LevelName = Parms.LevelName;
}


// Function BP_GUIFunction.BP_GUIFunction_C.SetupInputIcon
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPlatformRichTextBlock*           MessageIcon                                            (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, InstancedReference, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class URichTextBlock*                   Message                                                (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, InstancedReference, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             Icon                                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             Style                                                  (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_GUIFunction_C::SetupInputIcon(class UPlatformRichTextBlock*& MessageIcon, class URichTextBlock*& Message, const class FText& Icon, const class FText& Style, const class FText& Text, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BP_GUIFunction_C", "SetupInputIcon");

	Params::BP_GUIFunction_C_SetupInputIcon Parms{};

	Parms.MessageIcon = MessageIcon;
	Parms.Message = Message;
	Parms.Icon = std::move(Icon);
	Parms.Style = std::move(Style);
	Parms.Text = std::move(Text);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	MessageIcon = Parms.MessageIcon;
	Message = Parms.Message;
}


// Function BP_GUIFunction.BP_GUIFunction_C.CalcAnchors
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FAnchors                         OnwerPanelAnchors                                      (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FVector2D                        Pos                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector2D                        Size                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FAnchors                         CalcAnchors_0                                          (Parm, OutParm, NoDestructor)

void UBP_GUIFunction_C::CalcAnchors(const struct FAnchors& OnwerPanelAnchors, const struct FVector2D& Pos, const struct FVector2D& Size, class UObject* __WorldContext, struct FAnchors* CalcAnchors_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BP_GUIFunction_C", "CalcAnchors");

	Params::BP_GUIFunction_C_CalcAnchors Parms{};

	Parms.OnwerPanelAnchors = std::move(OnwerPanelAnchors);
	Parms.Pos = std::move(Pos);
	Parms.Size = std::move(Size);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (CalcAnchors_0 != nullptr)
		*CalcAnchors_0 = std::move(Parms.CalcAnchors_0);
}


// Function BP_GUIFunction.BP_GUIFunction_C.LoadDynamicLevel
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TSoftObjectPtr<class UWorld>            Level                                                  (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// bool                                    bVisible                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ULevelStreamingDynamic*           LevelInstance                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_GUIFunction_C::LoadDynamicLevel(TSoftObjectPtr<class UWorld> Level, bool bVisible, class UObject* __WorldContext, class ULevelStreamingDynamic** LevelInstance)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BP_GUIFunction_C", "LoadDynamicLevel");

	Params::BP_GUIFunction_C_LoadDynamicLevel Parms{};

	Parms.Level = Level;
	Parms.bVisible = bVisible;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (LevelInstance != nullptr)
		*LevelInstance = Parms.LevelInstance;
}


// Function BP_GUIFunction.BP_GUIFunction_C.UnLoadDynamicLevel
// (Static, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             LevelName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_GUIFunction_C::UnLoadDynamicLevel(class FName LevelName, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BP_GUIFunction_C", "UnLoadDynamicLevel");

	Params::BP_GUIFunction_C_UnLoadDynamicLevel Parms{};

	Parms.LevelName = LevelName;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}

}

