#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPB_NormalReplicate

#include "Basic.hpp"

#include "BPB_NormalReplicate_classes.hpp"
#include "BPB_NormalReplicate_parameters.hpp"


namespace SDK
{

// Function BPB_NormalReplicate.BPB_NormalReplicate_C.ExecuteUbergraph_BPB_NormalReplicate
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPB_NormalReplicate_C::ExecuteUbergraph_BPB_NormalReplicate(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPB_NormalReplicate_C", "ExecuteUbergraph_BPB_NormalReplicate");

	Params::BPB_NormalReplicate_C_ExecuteUbergraph_BPB_NormalReplicate Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPB_NormalReplicate.BPB_NormalReplicate_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPB_NormalReplicate_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPB_NormalReplicate_C", "ReceiveTick");

	Params::BPB_NormalReplicate_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPB_NormalReplicate.BPB_NormalReplicate_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABPB_NormalReplicate_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPB_NormalReplicate_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

