#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPB_CommonAttackLow

#include "Basic.hpp"

#include "BPB_CommonAttackLow_classes.hpp"
#include "BPB_CommonAttackLow_parameters.hpp"


namespace SDK
{

// Function BPB_CommonAttackLow.BPB_CommonAttackLow_C.ExecuteUbergraph_BPB_CommonAttackLow
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPB_CommonAttackLow_C::ExecuteUbergraph_BPB_CommonAttackLow(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPB_CommonAttackLow_C", "ExecuteUbergraph_BPB_CommonAttackLow");

	Params::BPB_CommonAttackLow_C_ExecuteUbergraph_BPB_CommonAttackLow Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPB_CommonAttackLow.BPB_CommonAttackLow_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPB_CommonAttackLow_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPB_CommonAttackLow_C", "ReceiveTick");

	Params::BPB_CommonAttackLow_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPB_CommonAttackLow.BPB_CommonAttackLow_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABPB_CommonAttackLow_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPB_CommonAttackLow_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

