#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPB_CommonShotNormal

#include "Basic.hpp"

#include "BPB_CommonShotNormal_classes.hpp"
#include "BPB_CommonShotNormal_parameters.hpp"


namespace SDK
{

// Function BPB_CommonShotNormal.BPB_CommonShotNormal_C.ExecuteUbergraph_BPB_CommonShotNormal
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPB_CommonShotNormal_C::ExecuteUbergraph_BPB_CommonShotNormal(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPB_CommonShotNormal_C", "ExecuteUbergraph_BPB_CommonShotNormal");

	Params::BPB_CommonShotNormal_C_ExecuteUbergraph_BPB_CommonShotNormal Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPB_CommonShotNormal.BPB_CommonShotNormal_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPB_CommonShotNormal_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPB_CommonShotNormal_C", "ReceiveTick");

	Params::BPB_CommonShotNormal_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPB_CommonShotNormal.BPB_CommonShotNormal_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABPB_CommonShotNormal_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPB_CommonShotNormal_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

