#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPG_CommonAttackLow

#include "Basic.hpp"

#include "BPG_CommonAttackLow_classes.hpp"
#include "BPG_CommonAttackLow_parameters.hpp"


namespace SDK
{

// Function BPG_CommonAttackLow.BPG_CommonAttackLow_C.ExecuteUbergraph_BPG_CommonAttackLow
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPG_CommonAttackLow_C::ExecuteUbergraph_BPG_CommonAttackLow(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPG_CommonAttackLow_C", "ExecuteUbergraph_BPG_CommonAttackLow");

	Params::BPG_CommonAttackLow_C_ExecuteUbergraph_BPG_CommonAttackLow Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPG_CommonAttackLow.BPG_CommonAttackLow_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void ABPG_CommonAttackLow_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPG_CommonAttackLow_C", "ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPG_CommonAttackLow.BPG_CommonAttackLow_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABPG_CommonAttackLow_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPG_CommonAttackLow_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPG_CommonAttackLow.BPG_CommonAttackLow_C.OnRep_ababa
// (BlueprintCallable, BlueprintEvent)

void ABPG_CommonAttackLow_C::OnRep_ababa()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPG_CommonAttackLow_C", "OnRep_ababa");

	UObject::ProcessEvent(Func, nullptr);
}

}

