#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPG_CommonShot

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "InGameModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPG_CommonShot.BPG_CommonShot_C
// 0x0010 (0x0460 - 0x0450)
class ABPG_CommonShot_C final : public AProjectileGeneratorBattle
{
public:
	uint8                                         Pad_448[0x8];                                      // 0x0448(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0450(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0458(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BPG_CommonShot(int32 EntryPoint);
	void OnSpawnInitParams();
	void ReceiveDestroyed();
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPG_CommonShot_C">();
	}
	static class ABPG_CommonShot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPG_CommonShot_C>();
	}
};
static_assert(alignof(ABPG_CommonShot_C) == 0x000010, "Wrong alignment on ABPG_CommonShot_C");
static_assert(sizeof(ABPG_CommonShot_C) == 0x000460, "Wrong size on ABPG_CommonShot_C");
static_assert(offsetof(ABPG_CommonShot_C, UberGraphFrame) == 0x000450, "Member 'ABPG_CommonShot_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABPG_CommonShot_C, DefaultSceneRoot) == 0x000458, "Member 'ABPG_CommonShot_C::DefaultSceneRoot' has a wrong offset!");

}

