#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KeyNotifyInterface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass KeyNotifyInterface.KeyNotifyInterface_C
// 0x0000 (0x0028 - 0x0028)
class IKeyNotifyInterface_C final : public IInterface
{
public:
	void PadInitialize();
	void PadTableListUp();
	void PadTableListDown();
	void PadDeInitialize();
	void PadReCopy();
	void PadReDownload();
	void PadClose();
	void PadTableSelect();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"KeyNotifyInterface_C">();
	}
	static class IKeyNotifyInterface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IKeyNotifyInterface_C>();
	}
};
static_assert(alignof(IKeyNotifyInterface_C) == 0x000008, "Wrong alignment on IKeyNotifyInterface_C");
static_assert(sizeof(IKeyNotifyInterface_C) == 0x000028, "Wrong size on IKeyNotifyInterface_C");

}

