#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TextChatList

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameModule_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_TextChatList.WBP_TextChatList_C
// 0x0010 (0x03B0 - 0x03A0)
class UWBP_TextChatList_C final : public UTextChatListWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	uint8                                         ChatType;                                          // 0x03A8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_TextChatList(int32 EntryPoint);
	void ClearEvent();
	void PreConstruct(bool IsDesignTime);
	void Construct();
	void UpdateList();
	void OnTeamUpChatReceivedEventDispatcherEvent(const class FString& PlayerId, const class FString& DisplayName, const class FString& Message, const bool bBlock);
	void AddItem(class UTextChatListObject* NewParam);
	void UpdateArray(class UTextChatListObject* NewParam);
	void Test();
	void SetUpUnreadMessage(class UTextChatListObject* NewParam);
	void UpdateUnreadMessage();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_TextChatList_C">();
	}
	static class UWBP_TextChatList_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TextChatList_C>();
	}
};
static_assert(alignof(UWBP_TextChatList_C) == 0x000008, "Wrong alignment on UWBP_TextChatList_C");
static_assert(sizeof(UWBP_TextChatList_C) == 0x0003B0, "Wrong size on UWBP_TextChatList_C");
static_assert(offsetof(UWBP_TextChatList_C, UberGraphFrame) == 0x0003A0, "Member 'UWBP_TextChatList_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_TextChatList_C, ChatType) == 0x0003A8, "Member 'UWBP_TextChatList_C::ChatType' has a wrong offset!");

}

