#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TextChat

#include "Basic.hpp"

#include "BykingUnrealModule_structs.hpp"
#include "UMG_structs.hpp"
#include "SlateCore_structs.hpp"
#include "GameModule_structs.hpp"
#include "UIFramework_structs.hpp"


namespace SDK::Params
{

// Function WBP_TextChat.WBP_TextChat_C.ExecuteUbergraph_WBP_TextChat
// 0x0110 (0x0110 - 0x0000)
struct WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UTextChatSubsystem*                     CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTextChatWidget*                        CallFunc_BP_GetTextChatWidget_ReturnValue;         // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTextChatSubsystem*                     CallFunc_GetGameInstanceSubsystem_ReturnValue_1;   // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0020(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0030(0x0010)(ZeroConstructor, NoDestructor)
	class UNetworkWork*                           CallFunc_GetGameInstanceSubsystem_ReturnValue_2;   // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPlatformSubsystem*                     CallFunc_GetGameInstanceSubsystem_ReturnValue_3;   // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BP_IsUGCUserPrivilege_ReturnValue;        // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EPlatform                                     CallFunc_GetPlatform_ReturnValue;                  // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0052(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BP_IsChatUserPrivilege_ReturnValue;       // 0x0053(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_CustomEvent_InVisibility;                   // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_55[0x3];                                       // 0x0055(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0058(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bPlaySound_1;                         // 0x0069(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bPlaySound;                           // 0x006A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Event_visivle;                              // 0x006B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETextChatLevelType                            K2Node_Event_LevelNam;                             // 0x006C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6D[0x3];                                       // 0x006D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x0070(0x0010)(ZeroConstructor, NoDestructor)
	const class UTextChatListObject*              K2Node_CustomEvent_chatObject;                     // 0x0080(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTextChatSubsystem*                     CallFunc_GetGameInstanceSubsystem_ReturnValue_4;   // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTextChatSubsystem*                     CallFunc_GetGameInstanceSubsystem_ReturnValue_5;   // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIngameWindowOpenFlag_ReturnValue;      // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_99[0x3];                                       // 0x0099(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x009C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_AC[0x4];                                       // 0x00AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAppWidget*                             K2Node_ComponentBoundEvent_widget;                 // 0x00B0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EWidgetInputType                              K2Node_ComponentBoundEvent_inputType;              // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_leftButton;             // 0x00B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_BA[0x2];                                       // 0x00BA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_5;            // 0x00BC(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(class UTextChatListObject* ChatObject)> K2Node_CreateDelegate_OutputDelegate_6;            // 0x00CC(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          K2Node_ComponentBoundEvent_bAgree;                 // 0x00DC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_DD[0x3];                                       // 0x00DD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_7;            // 0x00E0(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_8;            // 0x00F0(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(ESlateVisibility InVisibility)> K2Node_CreateDelegate_OutputDelegate_9;            // 0x0100(0x0010)(ZeroConstructor, NoDestructor)
};
static_assert(alignof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat) == 0x000008, "Wrong alignment on WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat");
static_assert(sizeof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat) == 0x000110, "Wrong size on WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, EntryPoint) == 0x000000, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x000008, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, CallFunc_BP_GetTextChatWidget_ReturnValue) == 0x000010, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::CallFunc_BP_GetTextChatWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, CallFunc_GetGameInstanceSubsystem_ReturnValue_1) == 0x000018, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::CallFunc_GetGameInstanceSubsystem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, K2Node_CreateDelegate_OutputDelegate) == 0x000020, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, K2Node_CreateDelegate_OutputDelegate_1) == 0x000030, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, CallFunc_GetGameInstanceSubsystem_ReturnValue_2) == 0x000040, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::CallFunc_GetGameInstanceSubsystem_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, CallFunc_GetGameInstanceSubsystem_ReturnValue_3) == 0x000048, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::CallFunc_GetGameInstanceSubsystem_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, CallFunc_BP_IsUGCUserPrivilege_ReturnValue) == 0x000050, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::CallFunc_BP_IsUGCUserPrivilege_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, CallFunc_GetPlatform_ReturnValue) == 0x000051, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::CallFunc_GetPlatform_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, K2Node_SwitchEnum_CmpSuccess) == 0x000052, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, CallFunc_BP_IsChatUserPrivilege_ReturnValue) == 0x000053, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::CallFunc_BP_IsChatUserPrivilege_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, K2Node_CustomEvent_InVisibility) == 0x000054, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::K2Node_CustomEvent_InVisibility' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, K2Node_CreateDelegate_OutputDelegate_2) == 0x000058, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000068, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, K2Node_Event_bPlaySound_1) == 0x000069, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::K2Node_Event_bPlaySound_1' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, K2Node_Event_bPlaySound) == 0x00006A, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::K2Node_Event_bPlaySound' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, K2Node_Event_visivle) == 0x00006B, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::K2Node_Event_visivle' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, K2Node_Event_LevelNam) == 0x00006C, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::K2Node_Event_LevelNam' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, K2Node_CreateDelegate_OutputDelegate_3) == 0x000070, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, K2Node_CustomEvent_chatObject) == 0x000080, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::K2Node_CustomEvent_chatObject' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, CallFunc_GetGameInstanceSubsystem_ReturnValue_4) == 0x000088, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::CallFunc_GetGameInstanceSubsystem_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, CallFunc_GetGameInstanceSubsystem_ReturnValue_5) == 0x000090, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::CallFunc_GetGameInstanceSubsystem_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, CallFunc_GetIngameWindowOpenFlag_ReturnValue) == 0x000098, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::CallFunc_GetIngameWindowOpenFlag_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, K2Node_CreateDelegate_OutputDelegate_4) == 0x00009C, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, K2Node_ComponentBoundEvent_widget) == 0x0000B0, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::K2Node_ComponentBoundEvent_widget' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, K2Node_ComponentBoundEvent_inputType) == 0x0000B8, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::K2Node_ComponentBoundEvent_inputType' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, K2Node_ComponentBoundEvent_leftButton) == 0x0000B9, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::K2Node_ComponentBoundEvent_leftButton' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, K2Node_CreateDelegate_OutputDelegate_5) == 0x0000BC, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, K2Node_CreateDelegate_OutputDelegate_6) == 0x0000CC, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::K2Node_CreateDelegate_OutputDelegate_6' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, K2Node_ComponentBoundEvent_bAgree) == 0x0000DC, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::K2Node_ComponentBoundEvent_bAgree' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, K2Node_CreateDelegate_OutputDelegate_7) == 0x0000E0, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::K2Node_CreateDelegate_OutputDelegate_7' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, K2Node_CreateDelegate_OutputDelegate_8) == 0x0000F0, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::K2Node_CreateDelegate_OutputDelegate_8' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat, K2Node_CreateDelegate_OutputDelegate_9) == 0x000100, "Member 'WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat::K2Node_CreateDelegate_OutputDelegate_9' has a wrong offset!");

// Function WBP_TextChat.WBP_TextChat_C.BndEvt__WBP_TextChat__consent_K2Node_ComponentBoundEvent_0_OnInputEventDelegate__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WBP_TextChat_C_BndEvt__WBP_TextChat__consent_K2Node_ComponentBoundEvent_0_OnInputEventDelegate__DelegateSignature final
{
public:
	bool                                          bAgree;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_TextChat_C_BndEvt__WBP_TextChat__consent_K2Node_ComponentBoundEvent_0_OnInputEventDelegate__DelegateSignature) == 0x000001, "Wrong alignment on WBP_TextChat_C_BndEvt__WBP_TextChat__consent_K2Node_ComponentBoundEvent_0_OnInputEventDelegate__DelegateSignature");
static_assert(sizeof(WBP_TextChat_C_BndEvt__WBP_TextChat__consent_K2Node_ComponentBoundEvent_0_OnInputEventDelegate__DelegateSignature) == 0x000001, "Wrong size on WBP_TextChat_C_BndEvt__WBP_TextChat__consent_K2Node_ComponentBoundEvent_0_OnInputEventDelegate__DelegateSignature");
static_assert(offsetof(WBP_TextChat_C_BndEvt__WBP_TextChat__consent_K2Node_ComponentBoundEvent_0_OnInputEventDelegate__DelegateSignature, bAgree) == 0x000000, "Member 'WBP_TextChat_C_BndEvt__WBP_TextChat__consent_K2Node_ComponentBoundEvent_0_OnInputEventDelegate__DelegateSignature::bAgree' has a wrong offset!");

// Function WBP_TextChat.WBP_TextChat_C.BndEvt__WBP_TextChat_ParentalControlWindow_K2Node_ComponentBoundEvent_2_OnWindowInputEventDelegate__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct WBP_TextChat_C_BndEvt__WBP_TextChat_ParentalControlWindow_K2Node_ComponentBoundEvent_2_OnWindowInputEventDelegate__DelegateSignature final
{
public:
	class UAppWidget*                             Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EWidgetInputType                              InputType;                                         // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          LeftButton;                                        // 0x0009(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_TextChat_C_BndEvt__WBP_TextChat_ParentalControlWindow_K2Node_ComponentBoundEvent_2_OnWindowInputEventDelegate__DelegateSignature) == 0x000008, "Wrong alignment on WBP_TextChat_C_BndEvt__WBP_TextChat_ParentalControlWindow_K2Node_ComponentBoundEvent_2_OnWindowInputEventDelegate__DelegateSignature");
static_assert(sizeof(WBP_TextChat_C_BndEvt__WBP_TextChat_ParentalControlWindow_K2Node_ComponentBoundEvent_2_OnWindowInputEventDelegate__DelegateSignature) == 0x000010, "Wrong size on WBP_TextChat_C_BndEvt__WBP_TextChat_ParentalControlWindow_K2Node_ComponentBoundEvent_2_OnWindowInputEventDelegate__DelegateSignature");
static_assert(offsetof(WBP_TextChat_C_BndEvt__WBP_TextChat_ParentalControlWindow_K2Node_ComponentBoundEvent_2_OnWindowInputEventDelegate__DelegateSignature, Widget) == 0x000000, "Member 'WBP_TextChat_C_BndEvt__WBP_TextChat_ParentalControlWindow_K2Node_ComponentBoundEvent_2_OnWindowInputEventDelegate__DelegateSignature::Widget' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_BndEvt__WBP_TextChat_ParentalControlWindow_K2Node_ComponentBoundEvent_2_OnWindowInputEventDelegate__DelegateSignature, InputType) == 0x000008, "Member 'WBP_TextChat_C_BndEvt__WBP_TextChat_ParentalControlWindow_K2Node_ComponentBoundEvent_2_OnWindowInputEventDelegate__DelegateSignature::InputType' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_BndEvt__WBP_TextChat_ParentalControlWindow_K2Node_ComponentBoundEvent_2_OnWindowInputEventDelegate__DelegateSignature, LeftButton) == 0x000009, "Member 'WBP_TextChat_C_BndEvt__WBP_TextChat_ParentalControlWindow_K2Node_ComponentBoundEvent_2_OnWindowInputEventDelegate__DelegateSignature::LeftButton' has a wrong offset!");

// Function WBP_TextChat.WBP_TextChat_C.OnTextChatRecieveEvent
// 0x0008 (0x0008 - 0x0000)
struct WBP_TextChat_C_OnTextChatRecieveEvent final
{
public:
	const class UTextChatListObject*              ChatObject;                                        // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TextChat_C_OnTextChatRecieveEvent) == 0x000008, "Wrong alignment on WBP_TextChat_C_OnTextChatRecieveEvent");
static_assert(sizeof(WBP_TextChat_C_OnTextChatRecieveEvent) == 0x000008, "Wrong size on WBP_TextChat_C_OnTextChatRecieveEvent");
static_assert(offsetof(WBP_TextChat_C_OnTextChatRecieveEvent, ChatObject) == 0x000000, "Member 'WBP_TextChat_C_OnTextChatRecieveEvent::ChatObject' has a wrong offset!");

// Function WBP_TextChat.WBP_TextChat_C.ChangeIconPosition
// 0x0001 (0x0001 - 0x0000)
struct WBP_TextChat_C_ChangeIconPosition final
{
public:
	ETextChatLevelType                            LevelNam;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TextChat_C_ChangeIconPosition) == 0x000001, "Wrong alignment on WBP_TextChat_C_ChangeIconPosition");
static_assert(sizeof(WBP_TextChat_C_ChangeIconPosition) == 0x000001, "Wrong size on WBP_TextChat_C_ChangeIconPosition");
static_assert(offsetof(WBP_TextChat_C_ChangeIconPosition, LevelNam) == 0x000000, "Member 'WBP_TextChat_C_ChangeIconPosition::LevelNam' has a wrong offset!");

// Function WBP_TextChat.WBP_TextChat_C.SetVisiblityNewMessage
// 0x0001 (0x0001 - 0x0000)
struct WBP_TextChat_C_SetVisiblityNewMessage final
{
public:
	ESlateVisibility                              Visivle;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TextChat_C_SetVisiblityNewMessage) == 0x000001, "Wrong alignment on WBP_TextChat_C_SetVisiblityNewMessage");
static_assert(sizeof(WBP_TextChat_C_SetVisiblityNewMessage) == 0x000001, "Wrong size on WBP_TextChat_C_SetVisiblityNewMessage");
static_assert(offsetof(WBP_TextChat_C_SetVisiblityNewMessage, Visivle) == 0x000000, "Member 'WBP_TextChat_C_SetVisiblityNewMessage::Visivle' has a wrong offset!");

// Function WBP_TextChat.WBP_TextChat_C.WindowClose
// 0x0001 (0x0001 - 0x0000)
struct WBP_TextChat_C_WindowClose final
{
public:
	bool                                          bPlaySound;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_TextChat_C_WindowClose) == 0x000001, "Wrong alignment on WBP_TextChat_C_WindowClose");
static_assert(sizeof(WBP_TextChat_C_WindowClose) == 0x000001, "Wrong size on WBP_TextChat_C_WindowClose");
static_assert(offsetof(WBP_TextChat_C_WindowClose, bPlaySound) == 0x000000, "Member 'WBP_TextChat_C_WindowClose::bPlaySound' has a wrong offset!");

// Function WBP_TextChat.WBP_TextChat_C.WindowOpen
// 0x0001 (0x0001 - 0x0000)
struct WBP_TextChat_C_WindowOpen final
{
public:
	bool                                          bPlaySound;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_TextChat_C_WindowOpen) == 0x000001, "Wrong alignment on WBP_TextChat_C_WindowOpen");
static_assert(sizeof(WBP_TextChat_C_WindowOpen) == 0x000001, "Wrong size on WBP_TextChat_C_WindowOpen");
static_assert(offsetof(WBP_TextChat_C_WindowOpen, bPlaySound) == 0x000000, "Member 'WBP_TextChat_C_WindowOpen::bPlaySound' has a wrong offset!");

// Function WBP_TextChat.WBP_TextChat_C.OnVisibilityChangedEvent
// 0x0001 (0x0001 - 0x0000)
struct WBP_TextChat_C_OnVisibilityChangedEvent final
{
public:
	ESlateVisibility                              InVisibility;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TextChat_C_OnVisibilityChangedEvent) == 0x000001, "Wrong alignment on WBP_TextChat_C_OnVisibilityChangedEvent");
static_assert(sizeof(WBP_TextChat_C_OnVisibilityChangedEvent) == 0x000001, "Wrong size on WBP_TextChat_C_OnVisibilityChangedEvent");
static_assert(offsetof(WBP_TextChat_C_OnVisibilityChangedEvent, InVisibility) == 0x000000, "Member 'WBP_TextChat_C_OnVisibilityChangedEvent::InVisibility' has a wrong offset!");

// Function WBP_TextChat.WBP_TextChat_C.ChangeBGVisibility
// 0x0020 (0x0020 - 0x0000)
struct WBP_TextChat_C_ChangeBGVisibility final
{
public:
	ESlateVisibility                              NewParam;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue;                 // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AHerovsGameState*                       K2Node_DynamicCast_AsHerovs_Game_State;            // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EGameModeType                                 CallFunc_GetGameModeType_ReturnValue;              // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x001A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_TextChat_C_ChangeBGVisibility) == 0x000008, "Wrong alignment on WBP_TextChat_C_ChangeBGVisibility");
static_assert(sizeof(WBP_TextChat_C_ChangeBGVisibility) == 0x000020, "Wrong size on WBP_TextChat_C_ChangeBGVisibility");
static_assert(offsetof(WBP_TextChat_C_ChangeBGVisibility, NewParam) == 0x000000, "Member 'WBP_TextChat_C_ChangeBGVisibility::NewParam' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ChangeBGVisibility, K2Node_SwitchEnum_CmpSuccess) == 0x000001, "Member 'WBP_TextChat_C_ChangeBGVisibility::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ChangeBGVisibility, CallFunc_GetGameState_ReturnValue) == 0x000008, "Member 'WBP_TextChat_C_ChangeBGVisibility::CallFunc_GetGameState_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ChangeBGVisibility, K2Node_DynamicCast_AsHerovs_Game_State) == 0x000010, "Member 'WBP_TextChat_C_ChangeBGVisibility::K2Node_DynamicCast_AsHerovs_Game_State' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ChangeBGVisibility, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'WBP_TextChat_C_ChangeBGVisibility::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ChangeBGVisibility, CallFunc_GetGameModeType_ReturnValue) == 0x000019, "Member 'WBP_TextChat_C_ChangeBGVisibility::CallFunc_GetGameModeType_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_ChangeBGVisibility, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x00001A, "Member 'WBP_TextChat_C_ChangeBGVisibility::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");

// Function WBP_TextChat.WBP_TextChat_C.TextChatRecieveEvent
// 0x0018 (0x0018 - 0x0000)
struct WBP_TextChat_C_TextChatRecieveEvent final
{
public:
	class UTextChatListObject*                    Velue;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTextChatSubsystem*                     CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BP_GetVisibleNewMessage_ReturnValue;      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetIngameWindowOpenFlag_ReturnValue;      // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_TextChat_C_TextChatRecieveEvent) == 0x000008, "Wrong alignment on WBP_TextChat_C_TextChatRecieveEvent");
static_assert(sizeof(WBP_TextChat_C_TextChatRecieveEvent) == 0x000018, "Wrong size on WBP_TextChat_C_TextChatRecieveEvent");
static_assert(offsetof(WBP_TextChat_C_TextChatRecieveEvent, Velue) == 0x000000, "Member 'WBP_TextChat_C_TextChatRecieveEvent::Velue' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_TextChatRecieveEvent, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x000008, "Member 'WBP_TextChat_C_TextChatRecieveEvent::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_TextChatRecieveEvent, CallFunc_BP_GetVisibleNewMessage_ReturnValue) == 0x000010, "Member 'WBP_TextChat_C_TextChatRecieveEvent::CallFunc_BP_GetVisibleNewMessage_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_TextChatRecieveEvent, CallFunc_GetIngameWindowOpenFlag_ReturnValue) == 0x000011, "Member 'WBP_TextChat_C_TextChatRecieveEvent::CallFunc_GetIngameWindowOpenFlag_ReturnValue' has a wrong offset!");

// Function WBP_TextChat.WBP_TextChat_C.OnOpenConsentEvent
// 0x0010 (0x0010 - 0x0000)
struct WBP_TextChat_C_OnOpenConsentEvent final
{
public:
	class UTextChatSubsystem*                     CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BP_IsAgreeFreeTextInput_ReturnValue;      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_TextChat_C_OnOpenConsentEvent) == 0x000008, "Wrong alignment on WBP_TextChat_C_OnOpenConsentEvent");
static_assert(sizeof(WBP_TextChat_C_OnOpenConsentEvent) == 0x000010, "Wrong size on WBP_TextChat_C_OnOpenConsentEvent");
static_assert(offsetof(WBP_TextChat_C_OnOpenConsentEvent, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x000000, "Member 'WBP_TextChat_C_OnOpenConsentEvent::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_OnOpenConsentEvent, CallFunc_BP_IsAgreeFreeTextInput_ReturnValue) == 0x000008, "Member 'WBP_TextChat_C_OnOpenConsentEvent::CallFunc_BP_IsAgreeFreeTextInput_ReturnValue' has a wrong offset!");

// Function WBP_TextChat.WBP_TextChat_C.On_BGImage_MouseButtonDown_0
// 0x0228 (0x0228 - 0x0000)
struct WBP_TextChat_C_On_BGImage_MouseButtonDown_0 final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FPointerEvent                          MouseEvent;                                        // 0x0038(0x0070)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FEventReply                            ReturnValue;                                       // 0x00A8(0x00B8)(Parm, OutParm, ReturnParm)
	struct FEventReply                            K2Node_MakeStruct_EventReply;                      // 0x0160(0x00B8)()
	bool                                          CallFunc_IsAnyAnimationPlaying_ReturnValue;        // 0x0218(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_219[0x7];                                      // 0x0219(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTextChatSubsystem*                     CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0220(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TextChat_C_On_BGImage_MouseButtonDown_0) == 0x000008, "Wrong alignment on WBP_TextChat_C_On_BGImage_MouseButtonDown_0");
static_assert(sizeof(WBP_TextChat_C_On_BGImage_MouseButtonDown_0) == 0x000228, "Wrong size on WBP_TextChat_C_On_BGImage_MouseButtonDown_0");
static_assert(offsetof(WBP_TextChat_C_On_BGImage_MouseButtonDown_0, MyGeometry) == 0x000000, "Member 'WBP_TextChat_C_On_BGImage_MouseButtonDown_0::MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_On_BGImage_MouseButtonDown_0, MouseEvent) == 0x000038, "Member 'WBP_TextChat_C_On_BGImage_MouseButtonDown_0::MouseEvent' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_On_BGImage_MouseButtonDown_0, ReturnValue) == 0x0000A8, "Member 'WBP_TextChat_C_On_BGImage_MouseButtonDown_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_On_BGImage_MouseButtonDown_0, K2Node_MakeStruct_EventReply) == 0x000160, "Member 'WBP_TextChat_C_On_BGImage_MouseButtonDown_0::K2Node_MakeStruct_EventReply' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_On_BGImage_MouseButtonDown_0, CallFunc_IsAnyAnimationPlaying_ReturnValue) == 0x000218, "Member 'WBP_TextChat_C_On_BGImage_MouseButtonDown_0::CallFunc_IsAnyAnimationPlaying_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TextChat_C_On_BGImage_MouseButtonDown_0, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x000220, "Member 'WBP_TextChat_C_On_BGImage_MouseButtonDown_0::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");

}

