#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_WindowButton

#include "Basic.hpp"

#include "WBP_WindowButton_classes.hpp"
#include "WBP_WindowButton_parameters.hpp"


namespace SDK
{

// Function WBP_WindowButton.WBP_WindowButton_C.ExecuteUbergraph_WBP_WindowButton
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_WindowButton_C::ExecuteUbergraph_WBP_WindowButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WindowButton_C", "ExecuteUbergraph_WBP_WindowButton");

	Params::WBP_WindowButton_C_ExecuteUbergraph_WBP_WindowButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_WindowButton.WBP_WindowButton_C.OnDecideDelegate_¤ÙóÈ_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAppWidget*                       Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EWidgetInputType                        InputType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_WindowButton_C::OnDecideDelegate______0(class UAppWidget* Widget, EWidgetInputType InputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WindowButton_C", "OnDecideDelegate_¤ÙóÈ_0");

	Params::WBP_WindowButton_C_OnDecideDelegate______0 Parms{};

	Parms.Widget = Widget;
	Parms.InputType = InputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_WindowButton.WBP_WindowButton_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_WindowButton_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WindowButton_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_WindowButton.WBP_WindowButton_C.UpdateArrow
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bUpView                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bDownView                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bLeftView                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bRightView                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_WindowButton_C::UpdateArrow(bool bUpView, bool bDownView, bool bLeftView, bool bRightView)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WindowButton_C", "UpdateArrow");

	Params::WBP_WindowButton_C_UpdateArrow Parms{};

	Parms.bUpView = bUpView;
	Parms.bDownView = bDownView;
	Parms.bLeftView = bLeftView;
	Parms.bRightView = bRightView;

	UObject::ProcessEvent(Func, &Parms);
}

}

