#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_VersionNotation

#include "Basic.hpp"

#include "UIFramework_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_VersionNotation.WBP_VersionNotation_C
// 0x0008 (0x0370 - 0x0368)
class UWBP_VersionNotation_C final : public UWidgetVersionNotation
{
public:
	class UInvalidationBox*                       InvalidationBox_0;                                 // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_VersionNotation_C">();
	}
	static class UWBP_VersionNotation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_VersionNotation_C>();
	}
};
static_assert(alignof(UWBP_VersionNotation_C) == 0x000008, "Wrong alignment on UWBP_VersionNotation_C");
static_assert(sizeof(UWBP_VersionNotation_C) == 0x000370, "Wrong size on UWBP_VersionNotation_C");
static_assert(offsetof(UWBP_VersionNotation_C, InvalidationBox_0) == 0x000368, "Member 'UWBP_VersionNotation_C::InvalidationBox_0' has a wrong offset!");

}

