#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TextChatWindow

#include "Basic.hpp"

#include "WBP_TextChatWindow_classes.hpp"
#include "WBP_TextChatWindow_parameters.hpp"


namespace SDK
{

// Function WBP_TextChatWindow.WBP_TextChatWindow_C.ExecuteUbergraph_WBP_TextChatWindow
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TextChatWindow_C::ExecuteUbergraph_WBP_TextChatWindow(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "ExecuteUbergraph_WBP_TextChatWindow");

	Params::WBP_TextChatWindow_C_ExecuteUbergraph_WBP_TextChatWindow Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C._onCallConcentEventDispather_¤ÙóÈ_0
// (BlueprintCallable, BlueprintEvent)

void UWBP_TextChatWindow_C::_onCallConcentEventDispather______0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "_onCallConcentEventDispather_¤ÙóÈ_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C._onSendableDelegate_¤ÙóÈ_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Commit                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// EPlatform                               Platform                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TextChatWindow_C::_onSendableDelegate______0(const bool Commit, EPlatform Platform)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "_onSendableDelegate_¤ÙóÈ_0");

	Params::WBP_TextChatWindow_C__onSendableDelegate______0 Parms{};

	Parms.Commit = Commit;
	Parms.Platform = Platform;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C._onFadeStartedDelegate_¤ÙóÈ_0
// (BlueprintCallable, BlueprintEvent)

void UWBP_TextChatWindow_C::_onFadeStartedDelegate______0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "_onFadeStartedDelegate_¤ÙóÈ_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.OnSendEvent
// (BlueprintCallable, BlueprintEvent)

void UWBP_TextChatWindow_C::OnSendEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "OnSendEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.BndEvt__WBP_TextChatWindow__iconButton_K2Node_ComponentBoundEvent_7_OnInputEventDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UAppWidget*                       Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EWidgetInputType                        InputType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TextChatWindow_C::BndEvt__WBP_TextChatWindow__iconButton_K2Node_ComponentBoundEvent_7_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType InputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "BndEvt__WBP_TextChatWindow__iconButton_K2Node_ComponentBoundEvent_7_OnInputEventDelegate__DelegateSignature");

	Params::WBP_TextChatWindow_C_BndEvt__WBP_TextChatWindow__iconButton_K2Node_ComponentBoundEvent_7_OnInputEventDelegate__DelegateSignature Parms{};

	Parms.Widget = Widget;
	Parms.InputType = InputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.BndEvt__WBP_TextChatWindow__iconButton_K2Node_ComponentBoundEvent_5_OnInputEventDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UAppWidget*                       Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EWidgetInputType                        InputType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TextChatWindow_C::BndEvt__WBP_TextChatWindow__iconButton_K2Node_ComponentBoundEvent_5_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType InputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "BndEvt__WBP_TextChatWindow__iconButton_K2Node_ComponentBoundEvent_5_OnInputEventDelegate__DelegateSignature");

	Params::WBP_TextChatWindow_C_BndEvt__WBP_TextChatWindow__iconButton_K2Node_ComponentBoundEvent_5_OnInputEventDelegate__DelegateSignature Parms{};

	Parms.Widget = Widget;
	Parms.InputType = InputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.OpenAnimEvent
// (BlueprintCallable, BlueprintEvent)

void UWBP_TextChatWindow_C::OpenAnimEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "OpenAnimEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.CloseAnimEvent
// (BlueprintCallable, BlueprintEvent)

void UWBP_TextChatWindow_C::CloseAnimEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "CloseAnimEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C._UpdateArrayEvent
// (BlueprintCallable, BlueprintEvent)

void UWBP_TextChatWindow_C::_UpdateArrayEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "_UpdateArrayEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.BndEvt__WBP_TextChatWindow__iconButton_K2Node_ComponentBoundEvent_1_OnInputEventDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UAppWidget*                       Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EWidgetInputType                        InputType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TextChatWindow_C::BndEvt__WBP_TextChatWindow__iconButton_K2Node_ComponentBoundEvent_1_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType InputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "BndEvt__WBP_TextChatWindow__iconButton_K2Node_ComponentBoundEvent_1_OnInputEventDelegate__DelegateSignature");

	Params::WBP_TextChatWindow_C_BndEvt__WBP_TextChatWindow__iconButton_K2Node_ComponentBoundEvent_1_OnInputEventDelegate__DelegateSignature Parms{};

	Parms.Widget = Widget;
	Parms.InputType = InputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.BndEvt__WBP_TextChatWindow__ChatSendButton_K2Node_ComponentBoundEvent_3_OnInputEventDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UAppWidget*                       Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EWidgetInputType                        InputType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TextChatWindow_C::BndEvt__WBP_TextChatWindow__ChatSendButton_K2Node_ComponentBoundEvent_3_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType InputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "BndEvt__WBP_TextChatWindow__ChatSendButton_K2Node_ComponentBoundEvent_3_OnInputEventDelegate__DelegateSignature");

	Params::WBP_TextChatWindow_C_BndEvt__WBP_TextChatWindow__ChatSendButton_K2Node_ComponentBoundEvent_3_OnInputEventDelegate__DelegateSignature Parms{};

	Parms.Widget = Widget;
	Parms.InputType = InputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.BndEvt__WBP_TextChatWindow__iconButton_K2Node_ComponentBoundEvent_0_OnInputEventDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UAppWidget*                       Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EWidgetInputType                        InputType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TextChatWindow_C::BndEvt__WBP_TextChatWindow__iconButton_K2Node_ComponentBoundEvent_0_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType InputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "BndEvt__WBP_TextChatWindow__iconButton_K2Node_ComponentBoundEvent_0_OnInputEventDelegate__DelegateSignature");

	Params::WBP_TextChatWindow_C_BndEvt__WBP_TextChatWindow__iconButton_K2Node_ComponentBoundEvent_0_OnInputEventDelegate__DelegateSignature Parms{};

	Parms.Widget = Widget;
	Parms.InputType = InputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.SetActiveSendButton
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsSendable                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_TextChatWindow_C::SetActiveSendButton(bool IsSendable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "SetActiveSendButton");

	Params::WBP_TextChatWindow_C_SetActiveSendButton Parms{};

	Parms.IsSendable = IsSendable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.ClearText
// (Event, Public, BlueprintEvent)

void UWBP_TextChatWindow_C::ClearText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "ClearText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.SetFocusInputTextBox
// (Event, Public, BlueprintEvent)

void UWBP_TextChatWindow_C::SetFocusInputTextBox()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "SetFocusInputTextBox");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.BndEvt__WBP_TextChatWindow__ChatSendButton_K2Node_ComponentBoundEvent_2_OnInputEventDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UAppWidget*                       Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EWidgetInputType                        InputType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TextChatWindow_C::BndEvt__WBP_TextChatWindow__ChatSendButton_K2Node_ComponentBoundEvent_2_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType InputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "BndEvt__WBP_TextChatWindow__ChatSendButton_K2Node_ComponentBoundEvent_2_OnInputEventDelegate__DelegateSignature");

	Params::WBP_TextChatWindow_C_BndEvt__WBP_TextChatWindow__ChatSendButton_K2Node_ComponentBoundEvent_2_OnInputEventDelegate__DelegateSignature Parms{};

	Parms.Widget = Widget;
	Parms.InputType = InputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.SetActiveTextInput
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    Input                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_TextChatWindow_C::SetActiveTextInput(bool Input)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "SetActiveTextInput");

	Params::WBP_TextChatWindow_C_SetActiveTextInput Parms{};

	Parms.Input = Input;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.OnChangeTextEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// bool                                    IsEmpty                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_TextChatWindow_C::OnChangeTextEvent(const class FText& Text, const bool IsEmpty)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "OnChangeTextEvent");

	Params::WBP_TextChatWindow_C_OnChangeTextEvent Parms{};

	Parms.Text = std::move(Text);
	Parms.IsEmpty = IsEmpty;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.OnAnimationStarted
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// class UWidgetAnimation*                 Animation                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TextChatWindow_C::OnAnimationStarted(const class UWidgetAnimation* Animation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "OnAnimationStarted");

	Params::WBP_TextChatWindow_C_OnAnimationStarted Parms{};

	Parms.Animation = Animation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.WindowClose
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bPlaySound                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_TextChatWindow_C::WindowClose(bool bPlaySound)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "WindowClose");

	Params::WBP_TextChatWindow_C_WindowClose Parms{};

	Parms.bPlaySound = bPlaySound;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.WindowOpen
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bPlaySound                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_TextChatWindow_C::WindowOpen(bool bPlaySound)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "WindowOpen");

	Params::WBP_TextChatWindow_C_WindowOpen Parms{};

	Parms.bPlaySound = bPlaySound;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.RecieveMessageIconEvent
// (BlueprintCallable, BlueprintEvent)

void UWBP_TextChatWindow_C::RecieveMessageIconEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "RecieveMessageIconEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_TextChatWindow_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_TextChatWindow_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "PreConstruct");

	Params::WBP_TextChatWindow_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.OnAnimationFinished
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// class UWidgetAnimation*                 Animation                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TextChatWindow_C::OnAnimationFinished(const class UWidgetAnimation* Animation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "OnAnimationFinished");

	Params::WBP_TextChatWindow_C_OnAnimationFinished Parms{};

	Parms.Animation = Animation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.checkTextEmpty
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// bool                                    NewParam                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_TextChatWindow_C::CheckTextEmpty(const class FText& Text, bool* NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "checkTextEmpty");

	Params::WBP_TextChatWindow_C_CheckTextEmpty Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = Parms.NewParam;
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.SetUpColor
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSlateColor                      NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_TextChatWindow_C::SetUpColor(const struct FSlateColor& NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "SetUpColor");

	Params::WBP_TextChatWindow_C_SetUpColor Parms{};

	Parms.NewParam = std::move(NewParam);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.SetupList
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_TextChatWindow_C::SetupList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "SetupList");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.OnAnalogValueChanged
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FAnalogInputEvent                InAnalogInputEvent                                     (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_TextChatWindow_C::OnAnalogValueChanged(const struct FGeometry& MyGeometry, const struct FAnalogInputEvent& InAnalogInputEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "OnAnalogValueChanged");

	Params::WBP_TextChatWindow_C_OnAnalogValueChanged Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InAnalogInputEvent = std::move(InAnalogInputEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.RequesetSendTeamUpChatTestCommand
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Message                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_TextChatWindow_C::RequesetSendTeamUpChatTestCommand(const class FText& Message)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "RequesetSendTeamUpChatTestCommand");

	Params::WBP_TextChatWindow_C_RequesetSendTeamUpChatTestCommand Parms{};

	Parms.Message = std::move(Message);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.SetUpPreviousFocusWidgets
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_TextChatWindow_C::SetUpPreviousFocusWidgets()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "SetUpPreviousFocusWidgets");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.SetFocusPreviousFocusWidgets
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_TextChatWindow_C::SetFocusPreviousFocusWidgets()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "SetFocusPreviousFocusWidgets");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.OnMouseWheel
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FPointerEvent                    MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_TextChatWindow_C::OnMouseWheel(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "OnMouseWheel");

	Params::WBP_TextChatWindow_C_OnMouseWheel Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.SetWidgetVisibility
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_TextChatWindow_C::SetWidgetVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "SetWidgetVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.Open
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    PlaySound_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_TextChatWindow_C::Open(bool PlaySound_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "Open");

	Params::WBP_TextChatWindow_C_Open Parms{};

	Parms.PlaySound_0 = PlaySound_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.Close
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    PlaySound_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_TextChatWindow_C::Close(bool PlaySound_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "Close");

	Params::WBP_TextChatWindow_C_Close Parms{};

	Parms.PlaySound_0 = PlaySound_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.CustomNavigationRight
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_TextChatWindow_C::CustomNavigationRight(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "CustomNavigationRight");

	Params::WBP_TextChatWindow_C_CustomNavigationRight Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.°¢p_0
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_TextChatWindow_C::___p_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "°¢p_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.OnKeyDown
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FKeyEvent                        InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_TextChatWindow_C::OnKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "OnKeyDown");

	Params::WBP_TextChatWindow_C_OnKeyDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.SequenceEvent__ENTRYPOINTWBP_TextChatWindow_0
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_TextChatWindow_C::SequenceEvent__ENTRYPOINTWBP_TextChatWindow_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "SequenceEvent__ENTRYPOINTWBP_TextChatWindow_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatWindow.WBP_TextChatWindow_C.SequenceEvent__ENTRYPOINTWBP_TextChatWindow_1
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_TextChatWindow_C::SequenceEvent__ENTRYPOINTWBP_TextChatWindow_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatWindow_C", "SequenceEvent__ENTRYPOINTWBP_TextChatWindow_1");

	UObject::ProcessEvent(Func, nullptr);
}

}

